apiVersion: apps/v1
kind: Deployment
metadata:
  name: clic-scheduler-center
spec:
  replicas: 1
  selector:
    matchLabels:
      clic: scheduler-center
  template:
    metadata:
      labels:
        clic: scheduler-center
    spec:
      containers:
        - name: scheduler-template
          image: edwardtang/scheduler-center:micro-service-rebuild
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args:
            - java -jar scheduler-center.jar --spring.profiles.active=pod
          volumeMounts:
            - name: nfs-volume
              mountPath: /data
          ports:
            - name: scheduler
              containerPort: 6666
            - name: notify
              containerPort: 8888
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: pvc-nfs