on:
  push:
    path:
      - 'thrift-gen/**'
      - 'common-utils/**'
      - 'executor-center/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run:
          mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f pom.xml
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.11
        with:
          # The name of the image you would like to push
          name: edwardtang/executor-center
          # The login username for the registry
          username: edwardtang
          # The login password for the registry
          password: daslab_system_group
          dockerfile: executor-center/Dockerfile
          tag_names: 'latest'